### ISSUE TITLE
Proxy.create is not a function with nodeJS v6

### ISSUE THREAD

**Issue by jfroffice** [ovh/node-ovh#9]
The callstack

```
    return Proxy.create(handler);
                 ^

TypeError: Proxy.create is not a function
    at Ovh.createRootProxy (/Users/user/Projects/xxxx/node_modules/ovh/lib/ovh.js:226:18)
    at new Ovh (/Users/user/Projects/xxxx/node_modules/ovh/lib/ovh.js:89:19)
    at module.exports (/Users/user/Projects/xxxx/node_modules/ovh/lib/ovh.js:658:12)
    at Object.<anonymous> (/Users/user/Projects/xxxx/service/helper/ovh/mailingList.js:7:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Projects/xxxx/service/helper/ovh/mailingLists.js:3:15)
    at Module._compile (module.js:541:32)
    at Object.Module._e
```

**Comment by bnjjj** [comment]
Thanks for your feedback, we're actually working to remove the dependency of this "Proxy" object. The node version 6 is very recent so it's not already update for this version.

**Comment by fgirardey** [comment]
+1, Node.js V6 is now released since 30 days 😅

**Comment by raunsbaekdk** [comment]
Have OVH abandoned this project?

**Comment by fgirardey** [comment]
I'm currently considering other SMS providers over OVH because of that not so active support

**Comment by bnjjj** [comment]
It's not abandoned. Could you tell me what's your usage of this API ? 

Do you use in the mode : 
```
ovh.request('GET', '/me', function (err, me) {
  console.log(err || me);
});
```

Or in this mode : 
```
ovh.me.$get(function (err, me) {
  console.log(err || me);
});
```

**Comment by fgirardey** [comment]
I used the first mode

**Comment by bnjjj** [comment]
Alright for the next week I'll release a major version without Proxy mode support :)

**Comment by bnjjj** [comment]
#10

**Comment by fgirardey** [comment]
Very good ! The promise support perfectly match my coding flow. Thank you, can't wait for the release !

**Comment by bnjjj** [comment]
Here it is, the V2.0.0 is out now https://www.npmjs.com/package/ovh 

Let me know if it fits your usage :)

**Comment by jfroffice** [comment]
works for me.
